<?php

namespace Database\Seeders;

use App\Models\Medicine;
use App\Models\Presentation;
use Illuminate\Database\Seeder;

class MedicineSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (Medicine::exists() || Presentation::count() < 52) {
            return;
        }

        $medicines = [
            [
                'name' => 'Paracetamol 500mg',
                'composition' => 'Paracetamol 500 mg',
                'description' => 'Analgésico y antipirético de uso común para el alivio del dolor leve a moderado y la fiebre.',
                'barcode' => '7501234560001',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Ibuprofeno 400mg',
                'composition' => 'Ibuprofeno 400 mg',
                'description' => 'Antiinflamatorio no esteroideo (AINE) indicado para el dolor, inflamación y fiebre.',
                'barcode' => '7501234560002',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Amoxicilina 500mg',
                'composition' => 'Amoxicilina trihidrato 500 mg',
                'description' => 'Antibiótico de amplio espectro del grupo de las penicilinas para infecciones bacterianas.',
                'barcode' => '7501234560003',
                'presentation_id' => 12,
            ],
            [
                'name' => 'Loratadina 10mg',
                'composition' => 'Loratadina 10 mg',
                'description' => 'Antihistamínico de segunda generación para el tratamiento de alergias y rinitis alérgica.',
                'barcode' => '7501234560004',
                'presentation_id' => 10,
            ],
            [
                'name' => 'Omeprazol 20mg',
                'composition' => 'Omeprazol 20 mg',
                'description' => 'Inhibidor de la bomba de protones para el tratamiento de gastritis y úlceras gástricas.',
                'barcode' => '7501234560005',
                'presentation_id' => 43,
            ],
            [
                'name' => 'Metformina 850mg',
                'composition' => 'Metformina clorhidrato 850 mg',
                'description' => 'Antidiabético oral de la clase de las biguanidas para el control de la glucemia en diabetes tipo 2.',
                'barcode' => '7501234560006',
                'presentation_id' => 42,
            ],
            [
                'name' => 'Enalapril 10mg',
                'composition' => 'Enalapril maleato 10 mg',
                'description' => 'Inhibidor de la ECA indicado para hipertensión arterial e insuficiencia cardíaca.',
                'barcode' => '7501234560007',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Atorvastatina 20mg',
                'composition' => 'Atorvastatina cálcica 20 mg',
                'description' => 'Estatina para reducir el colesterol LDL y triglicéridos en sangre.',
                'barcode' => '7501234560008',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Azitromicina 500mg',
                'composition' => 'Azitromicina dihidrato 500 mg',
                'description' => 'Antibiótico macrólido de amplio espectro para infecciones respiratorias y de tejidos blandos.',
                'barcode' => '7501234560009',
                'presentation_id' => 8,
            ],
            [
                'name' => 'Diclofenaco 50mg',
                'composition' => 'Diclofenaco sódico 50 mg',
                'description' => 'Antiinflamatorio no esteroideo para el dolor musculoesquelético, artritis y dismenorrea.',
                'barcode' => '7501234560010',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Ranitidina 150mg',
                'composition' => 'Ranitidina clorhidrato 150 mg',
                'description' => 'Antagonista H2 para el tratamiento de úlcera péptica y reflujo gastroesofágico.',
                'barcode' => '7501234560011',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Ciprofloxacino 500mg',
                'composition' => 'Ciprofloxacino clorhidrato 500 mg',
                'description' => 'Antibiótico fluoroquinolona de amplio espectro para infecciones urinarias, respiratorias y digestivas.',
                'barcode' => '7501234560012',
                'presentation_id' => 11,
            ],
            [
                'name' => 'Clonazepam 0.5mg',
                'composition' => 'Clonazepam 0.5 mg',
                'description' => 'Benzodiazepina indicada para el tratamiento de epilepsia, ataques de pánico y ansiedad.',
                'barcode' => '7501234560013',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Losartán 50mg',
                'composition' => 'Losartán potásico 50 mg',
                'description' => 'Antagonista del receptor de angiotensina II para el tratamiento de la hipertensión arterial.',
                'barcode' => '7501234560014',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Salbutamol Inhalador',
                'composition' => 'Salbutamol sulfato 100 mcg/dosis',
                'description' => 'Broncodilatador beta-2 agonista de acción corta para el alivio del broncoespasmo en asma.',
                'barcode' => '7501234560015',
                'presentation_id' => 1,
            ],
            [
                'name' => 'Insulina NPH 100 UI/ml',
                'composition' => 'Insulina isofánica humana 100 UI/ml',
                'description' => 'Insulina de acción intermedia para el control de la glucemia en pacientes con diabetes mellitus.',
                'barcode' => '7501234560016',
                'presentation_id' => 40,
            ],
            [
                'name' => 'Dexametasona 4mg/ml',
                'composition' => 'Dexametasona fosfato sódico 4 mg/ml',
                'description' => 'Corticosteroide potente para procesos inflamatorios, alérgicos y enfermedades autoinmunes.',
                'barcode' => '7501234560017',
                'presentation_id' => 25,
            ],
            [
                'name' => 'Ketorolaco 30mg/ml',
                'composition' => 'Ketorolaco trometamina 30 mg/ml',
                'description' => 'Analgésico AINE de uso parenteral para el dolor moderado a severo posoperatorio.',
                'barcode' => '7501234560018',
                'presentation_id' => 24,
            ],
            [
                'name' => 'Hidrocortisona Crema 1%',
                'composition' => 'Hidrocortisona acetato 1%',
                'description' => 'Corticosteroide tópico de baja potencia para dermatitis, eczema y picaduras de insectos.',
                'barcode' => '7501234560019',
                'presentation_id' => 30,
            ],
            [
                'name' => 'Clotrimazol Crema 1%',
                'composition' => 'Clotrimazol 1%',
                'description' => 'Antifúngico tópico para el tratamiento de micosis cutáneas, tiña y candidiasis.',
                'barcode' => '7501234560020',
                'presentation_id' => 31,
            ],
            [
                'name' => 'Metronidazol 500mg',
                'composition' => 'Metronidazol 500 mg',
                'description' => 'Antibiótico y antiparasitario para infecciones por bacterias anaerobias y protozoarios.',
                'barcode' => '7501234560021',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Clorfenamina 4mg',
                'composition' => 'Clorfenamina maleato 4 mg',
                'description' => 'Antihistamínico de primera generación para alergias, urticaria y rinitis alérgica.',
                'barcode' => '7501234560022',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Vitamina C 500mg',
                'composition' => 'Ácido ascórbico 500 mg',
                'description' => 'Suplemento vitamínico antioxidante para reforzar el sistema inmunológico.',
                'barcode' => '7501234560023',
                'presentation_id' => 3,
            ],
            [
                'name' => 'Complejo B',
                'composition' => 'Vitamina B1 100 mg, B6 200 mg, B12 200 mcg',
                'description' => 'Suplemento de vitaminas del complejo B para el sistema nervioso y metabolismo energético.',
                'barcode' => '7501234560024',
                'presentation_id' => 2,
            ],
            [
                'name' => 'Furosemida 40mg',
                'composition' => 'Furosemida 40 mg',
                'description' => 'Diurético de asa para el tratamiento del edema e hipertensión arterial.',
                'barcode' => '7501234560025',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Espironolactona 25mg',
                'composition' => 'Espironolactona 25 mg',
                'description' => 'Diurético ahorrador de potasio para insuficiencia cardíaca e hiperaldosteronismo.',
                'barcode' => '7501234560026',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Amlodipino 5mg',
                'composition' => 'Amlodipino besilato 5 mg',
                'description' => 'Bloqueador de canales de calcio para el tratamiento de hipertensión y angina de pecho.',
                'barcode' => '7501234560027',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Warfarina 5mg',
                'composition' => 'Warfarina sódica 5 mg',
                'description' => 'Anticoagulante oral para la prevención y tratamiento de tromboembolias venosas.',
                'barcode' => '7501234560028',
                'presentation_id' => 4,
            ],
            [
                'name' => 'Levotiroxina 100mcg',
                'composition' => 'Levotiroxina sódica 100 mcg',
                'description' => 'Hormona tiroidea sintética para el tratamiento del hipotiroidismo.',
                'barcode' => '7501234560029',
                'presentation_id' => 4,
            ],
            [
                'name' => 'Prednisona 20mg',
                'composition' => 'Prednisona 20 mg',
                'description' => 'Corticosteroide oral para procesos inflamatorios, alérgicos y enfermedades autoinmunes.',
                'barcode' => '7501234560030',
                'presentation_id' => 10,
            ],
            [
                'name' => 'Tramadol 50mg',
                'composition' => 'Tramadol clorhidrato 50 mg',
                'description' => 'Analgésico opioide de acción central para el tratamiento del dolor moderado a severo.',
                'barcode' => '7501234560031',
                'presentation_id' => 11,
            ],
            [
                'name' => 'Pantoprazol 40mg',
                'composition' => 'Pantoprazol sódico 40 mg',
                'description' => 'Inhibidor de la bomba de protones para esofagitis erosiva y síndrome de Zollinger-Ellison.',
                'barcode' => '7501234560032',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Fluconazol 150mg',
                'composition' => 'Fluconazol 150 mg',
                'description' => 'Antifúngico triazólico para candidiasis vaginal, oral y sistémica.',
                'barcode' => '7501234560033',
                'presentation_id' => 1,
            ],
            [
                'name' => 'Diazepam 5mg',
                'composition' => 'Diazepam 5 mg',
                'description' => 'Benzodiazepina para el tratamiento de ansiedad, espasmos musculares y abstinencia alcohólica.',
                'barcode' => '7501234560034',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Eritromicina 500mg',
                'composition' => 'Eritromicina estearato 500 mg',
                'description' => 'Antibiótico macrólido para infecciones respiratorias en pacientes alérgicos a penicilinas.',
                'barcode' => '7501234560035',
                'presentation_id' => 11,
            ],
            [
                'name' => 'Captopril 25mg',
                'composition' => 'Captopril 25 mg',
                'description' => 'Inhibidor de la ECA para hipertensión arterial e insuficiencia cardíaca congestiva.',
                'barcode' => '7501234560036',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Glibenclamida 5mg',
                'composition' => 'Glibenclamida 5 mg',
                'description' => 'Sulfonilurea hipoglucemiante oral para diabetes mellitus tipo 2.',
                'barcode' => '7501234560037',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Haloperidol 5mg',
                'composition' => 'Haloperidol 5 mg',
                'description' => 'Antipsicótico típico para el tratamiento de esquizofrenia y otros trastornos psicóticos.',
                'barcode' => '7501234560038',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Sertralina 50mg',
                'composition' => 'Sertralina clorhidrato 50 mg',
                'description' => 'Antidepresivo ISRS para depresión, trastorno obsesivo-compulsivo y trastorno de pánico.',
                'barcode' => '7501234560039',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Alprazolam 0.25mg',
                'composition' => 'Alprazolam 0.25 mg',
                'description' => 'Benzodiazepina de acción corta para trastornos de ansiedad y ataques de pánico.',
                'barcode' => '7501234560040',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Amiodarona 200mg',
                'composition' => 'Amiodarona clorhidrato 200 mg',
                'description' => 'Antiarrítmico para taquiarritmias ventriculares y supraventriculares graves.',
                'barcode' => '7501234560041',
                'presentation_id' => 3,
            ],
            [
                'name' => 'Ceftriaxona 1g',
                'composition' => 'Ceftriaxona sódica 1 g',
                'description' => 'Cefalosporina de tercera generación de amplio espectro para infecciones graves.',
                'barcode' => '7501234560042',
                'presentation_id' => 38,
            ],
            [
                'name' => 'Gentamicina 80mg/2ml',
                'composition' => 'Gentamicina sulfato 80 mg/2 ml',
                'description' => 'Aminoglucósido para infecciones graves por bacterias gram negativas.',
                'barcode' => '7501234560043',
                'presentation_id' => 24,
            ],
            [
                'name' => 'Dimenhidrinato 50mg',
                'composition' => 'Dimenhidrinato 50 mg',
                'description' => 'Antihistamínico para náuseas, vómitos y cinetosis (mareo por movimiento).',
                'barcode' => '7501234560044',
                'presentation_id' => 10,
            ],
            [
                'name' => 'Bisacodilo 5mg',
                'composition' => 'Bisacodilo 5 mg',
                'description' => 'Laxante estimulante para el tratamiento del estreñimiento ocasional.',
                'barcode' => '7501234560045',
                'presentation_id' => 44,
            ],
            [
                'name' => 'Supositorios de Glicerina',
                'composition' => 'Glicerina 3 g',
                'description' => 'Laxante osmótico rectal para el alivio rápido del estreñimiento.',
                'barcode' => '7501234560046',
                'presentation_id' => 45,
            ],
            [
                'name' => 'Nistatina Suspensión',
                'composition' => 'Nistatina 100,000 UI/ml',
                'description' => 'Antifúngico poliénico para el tratamiento de candidiasis oral e intestinal.',
                'barcode' => '7501234560047',
                'presentation_id' => 16,
            ],
            [
                'name' => 'Ambroxol Jarabe 15mg/5ml',
                'composition' => 'Ambroxol clorhidrato 15 mg/5 ml',
                'description' => 'Mucolítico y expectorante para fluidificar y eliminar secreciones bronquiales.',
                'barcode' => '7501234560048',
                'presentation_id' => 17,
            ],
            [
                'name' => 'Ibuprofeno Suspensión 200mg/5ml',
                'composition' => 'Ibuprofeno 200 mg/5 ml',
                'description' => 'Suspensión antiinflamatoria y analgésica pediátrica para fiebre y dolor leve a moderado.',
                'barcode' => '7501234560049',
                'presentation_id' => 17,
            ],
            [
                'name' => 'Paracetamol Jarabe 120mg/5ml',
                'composition' => 'Paracetamol 120 mg/5 ml',
                'description' => 'Jarabe analgésico y antipirético pediátrico para el alivio de la fiebre y el dolor.',
                'barcode' => '7501234560050',
                'presentation_id' => 17,
            ],
            [
                'name' => 'Sales de Rehidratación Oral',
                'composition' => 'Cloruro de sodio 2.6 g, Cloruro de potasio 1.5 g, Glucosa anhidra 13.5 g, Citrato trisódico 2.9 g',
                'description' => 'Solución rehidratante oral para la reposición de líquidos y electrolitos en diarrea.',
                'barcode' => '7501234560051',
                'presentation_id' => 34,
            ],
            [
                'name' => 'Bicarbonato de Sodio Sobre',
                'composition' => 'Bicarbonato de sodio 2 g',
                'description' => 'Antiácido sistémico y urinario para la acidez estomacal y alcalinización de orina.',
                'barcode' => '7501234560052',
                'presentation_id' => 34,
            ],
            [
                'name' => 'Hierro Ferroso 300mg',
                'composition' => 'Sulfato ferroso 300 mg (hierro elemental 60 mg)',
                'description' => 'Suplemento de hierro para el tratamiento y prevención de la anemia ferropénica.',
                'barcode' => '7501234560053',
                'presentation_id' => 3,
            ],
            [
                'name' => 'Ácido Fólico 5mg',
                'composition' => 'Ácido fólico 5 mg',
                'description' => 'Vitamina B9 para la prevención de defectos del tubo neural y tratamiento de anemias megaloblásticas.',
                'barcode' => '7501234560054',
                'presentation_id' => 4,
            ],
            [
                'name' => 'Calcio + Vitamina D3',
                'composition' => 'Carbonato de calcio 500 mg, Colecalciferol 400 UI',
                'description' => 'Suplemento de calcio y vitamina D para la prevención y tratamiento de osteoporosis.',
                'barcode' => '7501234560055',
                'presentation_id' => 4,
            ],
            [
                'name' => 'Betametasona 0.05% Crema',
                'composition' => 'Betametasona valerato 0.05%',
                'description' => 'Corticosteroide tópico de alta potencia para psoriasis, dermatitis y eczema severo.',
                'barcode' => '7501234560056',
                'presentation_id' => 31,
            ],
            [
                'name' => 'Tretinoína 0.025% Crema',
                'composition' => 'Tretinoína 0.025%',
                'description' => 'Retinoide tópico para el tratamiento del acné y fotoenvejecimiento cutáneo.',
                'barcode' => '7501234560057',
                'presentation_id' => 29,
            ],
            [
                'name' => 'Mupirocina 2% Ungüento',
                'composition' => 'Mupirocina 2%',
                'description' => 'Antibiótico tópico para impétigo e infecciones cutáneas bacterianas superficiales.',
                'barcode' => '7501234560058',
                'presentation_id' => 28,
            ],
            [
                'name' => 'Lidocaína 2% Gel',
                'composition' => 'Lidocaína clorhidrato 2%',
                'description' => 'Anestésico local tópico para procedimientos urológicos y analgesia de mucosas.',
                'barcode' => '7501234560059',
                'presentation_id' => 29,
            ],
            [
                'name' => 'Timolol 0.5% Colirio',
                'composition' => 'Timolol maleato 0.5%',
                'description' => 'Betabloqueador oftálmico para la reducción de la presión intraocular en glaucoma.',
                'barcode' => '7501234560060',
                'presentation_id' => 50,
            ],
            [
                'name' => 'Ciprofloxacino 0.3% Colirio',
                'composition' => 'Ciprofloxacino clorhidrato 0.3%',
                'description' => 'Antibiótico oftálmico para conjuntivitis bacteriana y úlceras corneales.',
                'barcode' => '7501234560061',
                'presentation_id' => 51,
            ],
            [
                'name' => 'Nafazolina 0.05% Colirio',
                'composition' => 'Nafazolina clorhidrato 0.05%',
                'description' => 'Vasoconstrictor oftálmico para el alivio de la hiperemia conjuntival (ojos rojos).',
                'barcode' => '7501234560062',
                'presentation_id' => 50,
            ],
            [
                'name' => 'Xilometazolina 0.1% Spray Nasal',
                'composition' => 'Xilometazolina clorhidrato 0.1%',
                'description' => 'Descongestionante nasal de acción rápida para rinitis y sinusitis.',
                'barcode' => '7501234560063',
                'presentation_id' => 51,
            ],
            [
                'name' => 'Beclometasona Spray Nasal',
                'composition' => 'Dipropionato de beclometasona 50 mcg/dosis',
                'description' => 'Corticosteroide nasal para el tratamiento de la rinitis alérgica estacional y perenne.',
                'barcode' => '7501234560064',
                'presentation_id' => 1,
            ],
            [
                'name' => 'Dioxido de Cloro Solución',
                'composition' => 'Dióxido de cloro 0.3%',
                'description' => 'Antiséptico bucal y desinfectante de uso tópico para heridas y mucosas.',
                'barcode' => '7501234560065',
                'presentation_id' => 19,
            ],
            [
                'name' => 'Yodo Povidona 10%',
                'composition' => 'Povidona yodada 10%',
                'description' => 'Antiséptico de amplio espectro para desinfección de heridas y preparación quirúrgica.',
                'barcode' => '7501234560066',
                'presentation_id' => 20,
            ],
            [
                'name' => 'Alcohol Isopropílico 70%',
                'composition' => 'Isopropanol 70% v/v',
                'description' => 'Antiséptico y desinfectante para piel e instrumentos médicos.',
                'barcode' => '7501234560067',
                'presentation_id' => 21,
            ],
            [
                'name' => 'Agua Oxigenada 10 Vol',
                'composition' => 'Peróxido de hidrógeno 3%',
                'description' => 'Antiséptico para limpieza de heridas y desinfección de tejidos superficiales.',
                'barcode' => '7501234560068',
                'presentation_id' => 22,
            ],
            [
                'name' => 'Enoxaparina 40mg/0.4ml',
                'composition' => 'Enoxaparina sódica 40 mg/0.4 ml',
                'description' => 'Heparina de bajo peso molecular para la prevención de tromboembolismo venoso.',
                'barcode' => '7501234560069',
                'presentation_id' => 23,
            ],
            [
                'name' => 'Adrenalina 1mg/ml',
                'composition' => 'Epinefrina clorhidrato 1 mg/ml',
                'description' => 'Catecolamina de emergencia para anafilaxia, paro cardíaco y broncoespasmo severo.',
                'barcode' => '7501234560070',
                'presentation_id' => 23,
            ],
            [
                'name' => 'Atropina 0.5mg/ml',
                'composition' => 'Atropina sulfato 0.5 mg/ml',
                'description' => 'Anticolinérgico para bradicardia sinusal, espasmos gastrointestinales y preanestesia.',
                'barcode' => '7501234560071',
                'presentation_id' => 24,
            ],
            [
                'name' => 'Morfina 10mg/ml',
                'composition' => 'Morfina sulfato 10 mg/ml',
                'description' => 'Opioide mayor de referencia para el tratamiento del dolor severo e infarto de miocardio.',
                'barcode' => '7501234560072',
                'presentation_id' => 25,
            ],
            [
                'name' => 'Metoclopramida 10mg/2ml',
                'composition' => 'Metoclopramida clorhidrato 10 mg/2 ml',
                'description' => 'Procinético y antiemético para náuseas, vómitos y gastroparesia.',
                'barcode' => '7501234560073',
                'presentation_id' => 24,
            ],
            [
                'name' => 'Ondansetrón 4mg/2ml',
                'composition' => 'Ondansetrón clorhidrato 4 mg/2 ml',
                'description' => 'Antiemético antagonista 5-HT3 para náuseas y vómitos por quimioterapia y cirugía.',
                'barcode' => '7501234560074',
                'presentation_id' => 24,
            ],
            [
                'name' => 'Cefalexina 500mg',
                'composition' => 'Cefalexina monohidrato 500 mg',
                'description' => 'Cefalosporina de primera generación para infecciones de piel, urinarias y respiratorias.',
                'barcode' => '7501234560075',
                'presentation_id' => 11,
            ],
            [
                'name' => 'Claritromicina 500mg',
                'composition' => 'Claritromicina 500 mg',
                'description' => 'Antibiótico macrólido para infecciones del tracto respiratorio superior e inferior.',
                'barcode' => '7501234560076',
                'presentation_id' => 9,
            ],
            [
                'name' => 'Doxiciclina 100mg',
                'composition' => 'Doxiciclina hiclatol 100 mg',
                'description' => 'Tetraciclina de amplio espectro para infecciones por Chlamydia, Rickettsia y acné.',
                'barcode' => '7501234560077',
                'presentation_id' => 11,
            ],
            [
                'name' => 'Nitroglicerina Parche 5mg',
                'composition' => 'Nitroglicerina 5 mg/24h',
                'description' => 'Nitrato transdérmico para la prevención de angina de pecho crónica estable.',
                'barcode' => '7501234560078',
                'presentation_id' => 49,
            ],
            [
                'name' => 'Fentanilo Parche 25mcg/h',
                'composition' => 'Fentanilo 25 mcg/h',
                'description' => 'Opioide transdérmico para el dolor crónico severo en pacientes con cáncer.',
                'barcode' => '7501234560079',
                'presentation_id' => 47,
            ],
            [
                'name' => 'Aciclovir 200mg',
                'composition' => 'Aciclovir 200 mg',
                'description' => 'Antiviral para el tratamiento de infecciones por herpes simple y herpes zóster.',
                'barcode' => '7501234560080',
                'presentation_id' => 5,
            ],
            [
                'name' => 'Aciclovir Crema 5%',
                'composition' => 'Aciclovir 5%',
                'description' => 'Antiviral tópico para el tratamiento del herpes labial y herpes genital recurrente.',
                'barcode' => '7501234560081',
                'presentation_id' => 28,
            ],
            [
                'name' => 'Zinc Óxido 20% Crema',
                'composition' => 'Óxido de zinc 20%',
                'description' => 'Protector cutáneo y antiséptico suave para dermatitis del pañal e irritaciones.',
                'barcode' => '7501234560082',
                'presentation_id' => 31,
            ],
            [
                'name' => 'Permetrina 5% Crema',
                'composition' => 'Permetrina 5%',
                'description' => 'Antiparasitario tópico para el tratamiento de la sarna (escabiosis) y pediculosis.',
                'barcode' => '7501234560083',
                'presentation_id' => 31,
            ],
            [
                'name' => 'Albendazol 200mg',
                'composition' => 'Albendazol 200 mg',
                'description' => 'Antiparasitario de amplio espectro para giardiasis, ascariasis y otras parasitosis.',
                'barcode' => '7501234560084',
                'presentation_id' => 9,
            ],
            [
                'name' => 'Mebendazol 500mg',
                'composition' => 'Mebendazol 500 mg',
                'description' => 'Antiparasitario para el tratamiento de oxiuros, áscaris, tricocéfalos y anquilostomas.',
                'barcode' => '7501234560085',
                'presentation_id' => 1,
            ],
            [
                'name' => 'Misoprostol 200mcg',
                'composition' => 'Misoprostol 200 mcg',
                'description' => 'Análogo de prostaglandina para prevención de úlceras por AINEs y maduración cervical.',
                'barcode' => '7501234560086',
                'presentation_id' => 8,
            ],
            [
                'name' => 'Bromhexina 8mg',
                'composition' => 'Bromhexina clorhidrato 8 mg',
                'description' => 'Mucolítico para el tratamiento de la tos productiva con secreciones viscosas.',
                'barcode' => '7501234560087',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Terbutalina 2.5mg',
                'composition' => 'Terbutalina sulfato 2.5 mg',
                'description' => 'Broncodilatador beta-2 agonista para el tratamiento del asma bronquial y EPOC.',
                'barcode' => '7501234560088',
                'presentation_id' => 13,
            ],
            [
                'name' => 'Prednisolona 15mg/5ml Solución',
                'composition' => 'Prednisolona 15 mg/5 ml',
                'description' => 'Corticosteroide líquido pediátrico para asma, alergias y procesos inflamatorios.',
                'barcode' => '7501234560089',
                'presentation_id' => 16,
            ],
            [
                'name' => 'Nifedipino 10mg',
                'composition' => 'Nifedipino 10 mg',
                'description' => 'Bloqueador de canales de calcio para hipertensión arterial y angina de pecho.',
                'barcode' => '7501234560090',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Propranolol 40mg',
                'composition' => 'Propranolol clorhidrato 40 mg',
                'description' => 'Betabloqueador no selectivo para hipertensión, angina, arritmias y migraña.',
                'barcode' => '7501234560091',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Digoxina 0.25mg',
                'composition' => 'Digoxina 0.25 mg',
                'description' => 'Glucósido cardíaco para insuficiencia cardíaca y fibrilación auricular.',
                'barcode' => '7501234560092',
                'presentation_id' => 4,
            ],
            [
                'name' => 'Litio Carbonato 300mg',
                'composition' => 'Carbonato de litio 300 mg',
                'description' => 'Estabilizador del ánimo para el tratamiento del trastorno bipolar.',
                'barcode' => '7501234560093',
                'presentation_id' => 4,
            ],
            [
                'name' => 'Fluoxetina 20mg',
                'composition' => 'Fluoxetina clorhidrato 20 mg',
                'description' => 'Antidepresivo ISRS para depresión mayor, bulimia nerviosa y TOC.',
                'barcode' => '7501234560094',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Risperidona 2mg',
                'composition' => 'Risperidona 2 mg',
                'description' => 'Antipsicótico atípico para esquizofrenia, trastorno bipolar y autismo.',
                'barcode' => '7501234560095',
                'presentation_id' => 14,
            ],
            [
                'name' => 'Piridoxina 50mg',
                'composition' => 'Piridoxina clorhidrato 50 mg (Vitamina B6)',
                'description' => 'Vitamina B6 para la prevención y tratamiento de la deficiencia de piridoxina y náuseas del embarazo.',
                'barcode' => '7501234560096',
                'presentation_id' => 3,
            ],
            [
                'name' => 'Ranitidina Jarabe 75mg/5ml',
                'composition' => 'Ranitidina clorhidrato 75 mg/5 ml',
                'description' => 'Antagonista H2 pediátrico para reflujo gastroesofágico y úlcera péptica en niños.',
                'barcode' => '7501234560097',
                'presentation_id' => 17,
            ],
            [
                'name' => 'Eritromicina Suspensión 250mg/5ml',
                'composition' => 'Eritromicina etilsuccinato 250 mg/5 ml',
                'description' => 'Antibiótico macrólido pediátrico para infecciones respiratorias y cutáneas.',
                'barcode' => '7501234560098',
                'presentation_id' => 18,
            ],
            [
                'name' => 'Sulfametoxazol + Trimetoprim 800/160mg',
                'composition' => 'Sulfametoxazol 800 mg + Trimetoprim 160 mg',
                'description' => 'Antibiótico sulfonamida para infecciones urinarias, respiratorias y digestivas.',
                'barcode' => '7501234560099',
                'presentation_id' => 11,
            ],
            [
                'name' => 'Hierro Sacarosa 100mg/5ml',
                'composition' => 'Hierro sacarosa 100 mg/5 ml',
                'description' => 'Hierro intravenoso para anemia ferropénica severa en pacientes que no toleran la vía oral.',
                'barcode' => '7501234560100',
                'presentation_id' => 26,
            ],
        ];

        foreach ($medicines as $medicine) {
            Medicine::create($medicine);
        }
    }
}
